# Generated by Django 5.1.3 on 2024-11-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0007_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.CharField(choices=[('test_based', 'test_based'), ('developer_based', 'developer_based'), ('multi-discipline', 'multi-discipline')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
