# Generated by Django 5.1.3 on 2024-12-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0008_alter_courses_category_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='mentor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
